# Site settings
title: Prudio - Communicate with your website visitors through Slack
email: hello@prud.io
description: > # this means to ignore newlines until "baseurl:"
  Prudio is the easiest way to engage your website visitors through Slack.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.prud.io" # the base hostname & protocol for your site
twitter_username: prudioHQ
github_username:  prudioHQ

# Build settings
markdown: kramdown
